#!/bin/bash
ln -sf ${1}_gwen_scaffolds_001-01.g.vcf.gz 001-01.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_069-02.g.vcf.gz 069-02.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_263-C.g.vcf.gz 263-C.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Anaheim.merged.g.vcf.gz Anaheim.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Bacon.merged.g.vcf.gz Bacon.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Carlsbad.merged.g.vcf.gz Carlsbad.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_CH-CR-25.g.vcf.gz CH-CR-25.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_CH-G-07.g.vcf.gz CH-G-07.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_CH-G-10.g.vcf.gz CH-G-10.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_CH-G-11.g.vcf.gz CH-G-11.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_CH-GU-01.g.vcf.gz CH-GU-01.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Fairchild.merged.g.vcf.gz Fairchild.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Fuerte_1.merged.g.vcf.gz Fuerte.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Ganter.merged.g.vcf.gz Ganter.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Guaslipe.merged.g.vcf.gz Guaslipe.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Gwen.merged.g.vcf.gz Gwen.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Hass.merged.g.vcf.gz Hass.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Linda.merged.g.vcf.gz Linda.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Lyon.merged.g.vcf.gz Lyon.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Mendez.g.vcf.gz Mendez.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Nabal.merged.g.vcf.gz Nabal.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Nimlioh.merged.g.vcf.gz Nimlioh.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Ocotea_bothanthra.merged.g.vcf.gz Ocotea_bothanthra.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_PequenoCharly.g.vcf.gz PequenoCharly.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Persea_donnell_smithii.merged.g.vcf.gz Persea_donnell_smithii.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Persea_hintonii.merged.g.vcf.gz Persea_hintonii.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Pinkerton.merged.g.vcf.gz Pinkerton.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Reed.merged.g.vcf.gz Reed.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Simmonds.merged.g.vcf.gz Simmonds.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Taft.merged.g.vcf.gz Taft.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Thille.merged.g.vcf.gz Thille.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_TopaTopa.merged.g.vcf.gz TopaTopa.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_VC26.merged.g.vcf.gz VC26.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Velvick.g.vcf.gz Velvick.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Waldin.merged.g.vcf.gz Waldin.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_Zutano.merged.g.vcf.gz Zutano.g.vcf.gz
ln -sf ${1}_gwen_scaffolds_001-01.g.vcf.idx 001-01.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_069-02.g.vcf.idx 069-02.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_263-C.g.vcf.idx 263-C.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Anaheim.merged.g.vcf.idx Anaheim.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Bacon.merged.g.vcf.idx Bacon.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Carlsbad.merged.g.vcf.idx Carlsbad.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_CH-CR-25.g.vcf.idx CH-CR-25.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_CH-G-07.g.vcf.idx CH-G-07.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_CH-G-10.g.vcf.idx CH-G-10.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_CH-G-11.g.vcf.idx CH-G-11.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_CH-GU-01.g.vcf.idx CH-GU-01.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Fairchild.merged.g.vcf.idx Fairchild.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Fuerte_1.merged.g.vcf.idx Fuerte.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Ganter.merged.g.vcf.idx Ganter.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Guaslipe.merged.g.vcf.idx Guaslipe.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Gwen.merged.g.vcf.idx Gwen.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Hass.merged.g.vcf.idx Hass.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Linda.merged.g.vcf.idx Linda.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Lyon.merged.g.vcf.idx Lyon.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Mendez.g.vcf.idx Mendez.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Nabal.merged.g.vcf.idx Nabal.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Nimlioh.merged.g.vcf.idx Nimlioh.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Ocotea_bothanthra.merged.g.vcf.idx Ocotea_bothanthra.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_PequenoCharly.g.vcf.idx PequenoCharly.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Persea_donnell_smithii.merged.g.vcf.idx Persea_donnell_smithii.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Persea_hintonii.merged.g.vcf.idx Persea_hintonii.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Pinkerton.merged.g.vcf.idx Pinkerton.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Reed.merged.g.vcf.idx Reed.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Simmonds.merged.g.vcf.idx Simmonds.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Taft.merged.g.vcf.idx Taft.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Thille.merged.g.vcf.idx Thille.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_TopaTopa.merged.g.vcf.idx TopaTopa.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_VC26.merged.g.vcf.idx VC26.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Velvick.g.vcf.idx Velvick.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Waldin.merged.g.vcf.idx Waldin.g.vcf.idx
ln -sf ${1}_gwen_scaffolds_Zutano.merged.g.vcf.idx Zutano.g.vcf.idx
